### PR TITLE
Change mirrorlist links to raw.github as http://mirrorlist.repoforge.…

### PR DESCRIPTION
**Pull request by cvakiitho**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

…org/ is down.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tas50** [comment]
Any chance you can change the URLs over to https://github.com/repoforge/mirrorlist. I realize it's actually a fork, but that gives it a bit of credibility.

**Comment by cvakiitho** [comment]
@tas50 hmm actually that is the reason why the original mirrorlist doesn't work,
generated github pages page is linked to this fork, and some autodeploy script removed all mirros.: 

https://github.com/repoforge/mirrorlist/commit/6d8c3454c39cf353b90422a6e5f76d97ae22775e

**Comment by cvakiitho** [comment]
Created PR https://github.com/repoforge/mirrorlist/pull/2

**Comment by cvakiitho** [comment]
repoforge mirrorlist is fixed, no need to update urls.

**Pull request closed without merging**
